# Generated by Django 5.0.6 on 2024-06-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0003_delete_mybooks"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyBooks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=60)),
                ("about", models.TextField()),
                ("price", models.FloatField()),
                ("image", models.ImageField(upload_to="books_images")),
                ("stars", models.CharField(max_length=1)),
            ],
        ),
    ]
