# Generated by Django 5.0.6 on 2024-06-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0005_alter_mybooks_stars"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("birth", models.DateField()),
                ("image", models.ImageField(upload_to="my_images")),
                ("profession", models.CharField(max_length=20)),
                ("about_me", models.TextField()),
                ("phone_number", models.CharField(max_length=30)),
                ("instagram", models.CharField(max_length=30)),
                ("telegram", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("linkedin", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
