# Generated by Django 5.0.6 on 2024-06-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0006_aboutme_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutme",
            name="instagram",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="aboutme",
            name="linkedin",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="aboutme",
            name="telegram",
            field=models.CharField(max_length=60),
        ),
    ]
