# Generated by Django 5.0.6 on 2024-06-18 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0007_alter_aboutme_instagram_alter_aboutme_linkedin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutme",
            name="profession",
        ),
    ]
