# Generated by Django 5.0.6 on 2024-06-18 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0008_remove_aboutme_profession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutMe",
        ),
    ]
